### ISSUE TITLE
Diagram of automation in harden image. 

### ISSUE THREAD

**Issue by jcanales** [k8-proxy/k8-security#101]

**Comment by virajut** [comment]
Here is the first version of the diagram representing the overview of Hardening process automation

![GW_Image_Hardening_Automation](https://user-images.githubusercontent.com/22414128/95751564-6dc5da00-0cbc-11eb-9029-587d243ea2cc.png)

**Comment by virajut** [comment]
https://docs.google.com/document/d/16MvYc9XV8SmdXsbWjSdHlhO5TQ5xnGGjicuUuw_mCJc/edit?usp=sharing
