### ISSUE TITLE
Hardening docker images (research)

### ISSUE THREAD

**Issue by jcanales** [k8-proxy/k8-security#22]

**Comment by michaelhidalgo** [comment]
CIS is great because they have their own benchmark. They also have already hardened images as described here https://www.cisecurity.org/cis-hardened-images/.

The only problem is that they are cloud-based images (aka images for AWS, Azure, GCP). I'm investigating if they have standalone hardened images for our purposes.


[CIS_Docker_Benchmark_v1.2.0.pdf](https://github.com/k8-proxy/k8-security/files/5235820/CIS_Docker_Benchmark_v1.2.0.pdf)

**Comment by michaelhidalgo** [comment]
Also OWASP great CheatSheet 

https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html

**Comment by michaelhidalgo** [comment]
As per Abbas CentOS-7-x86_64-Minimal-2003.iso is the version of OS we need to harden.

I believe the best way is to follow CIS standard. Here is the CENTOS 7 Benchmark version 3.0.0 for reference.

[CIS_CentOS_Linux_7_Benchmark_v3.0.0.pdf](https://github.com/k8-proxy/k8-security/files/5239018/CIS_CentOS_Linux_7_Benchmark_v3.0.0.pdf)

**Comment by michaelhidalgo** [comment]
I'm working on comparing CIS Centos Benchmark version 2 and 3 (to determine which one should be used) and also defining which levels should be good to implement considering the https://github.com/filetrust/program-icap/wiki/Abridged-Amendment-3

**Comment by michaelhidalgo** [comment]
Hey @JameelNabbo  here is the scaffolding

`# using centos minimal centos:7.8.2003

FROM centos:7.8.2003
 
LABEL version = "1.0.0"
LABEL author =  "Michael Hidalgo" 

RUN yum -y update; yum clean all
RUN yum -y install epel-release; yum clean all
# this section patches the libraries




CMD ["echo", "Hello, World"]
`

**Comment by michaelhidalgo** [comment]
Hey @JameelNabbo , @beaviss so I spent some time on the option # 2 from the proposal:

**Create a DockerFile from the centos:7.8.2003 and run the patching.** However, this might not work as per Docker documentation, [they state](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

_**Avoid RUN apt-get upgrade and dist-upgrade, as many of the “essential” packages from the parent images, cannot upgrade inside an unprivileged container**. If a package contained in the parent image is out-of-date, contact its maintainers. If you know there is a particular package, foo, that needs to be updated, use apt-get install -y foo to update automatically._

When we run the yum update from the build process, it cannot patch one of the libraries flagged as High by trivy. I show this error **Failed to get D-Bus connection: Operation not permitted.**

```
Dependencies Resolved

================================================================================
 Package                    Arch     Version                    Repository
                                                                           Size
================================================================================
Updating:
 bind-license               noarch   32:9.11.4-16.P2.el7_8.6    updates    90 k
 binutils                   x86_64   2.27-43.base.el7_8.1       updates   5.9 M
 ca-certificates            noarch   2020.2.41-70.0.el7_8       updates   382 k
 curl                       x86_64   7.29.0-57.el7_8.1          updates   271 k
 dbus                       x86_64   1:1.10.24-14.el7_8         updates   245 k
 dbus-libs                  x86_64   1:1.10.24-14.el7_8         updates   169 k
 device-mapper              x86_64   7:1.02.164-7.el7_8.2       updates   295 k
 device-mapper-libs         x86_64   7:1.02.164-7.el7_8.2       updates   324 k
 libcurl                    x86_64   7.29.0-57.el7_8.1          updates   223 k
 systemd                    x86_64   219-73.el7_8.9             updates   5.1 M
 systemd-libs               x86_64   219-73.el7_8.9             updates   416 k
 tzdata                     noarch   2020a-1.el7                updates   495 k
 yum-plugin-fastestmirror   noarch   1.1.31-54.el7_8            updates    34 k
 yum-plugin-ovl             noarch   1.1.31-54.el7_8            updates    28 k
 yum-utils                  noarch   1.1.31-54.el7_8            updates   122 k

Transaction Summary
================================================================================
Upgrade  15 Packages

Total download size: 14 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/updates/packages/bind-license-9.11.4-16.P2.el7_8.6.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for bind-license-9.11.4-16.P2.el7_8.6.noarch.rpm is not installed
--------------------------------------------------------------------------------
Total                                              242 kB/s |  14 MB  00:59     
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-8.2003.0.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : systemd-libs-219-73.el7_8.9.x86_64                          1/30 
  Updating   : libcurl-7.29.0-57.el7_8.1.x86_64                            2/30 
  Updating   : 1:dbus-libs-1.10.24-14.el7_8.x86_64                         3/30 
  Updating   : systemd-219-73.el7_8.9.x86_64                               4/30 
Failed to get D-Bus connection: Operation not permitted
  Updating   : 1:dbus-1.10.24-14.el7_8.x86_64                              5/30 
  Updating   : 7:device-mapper-libs-1.02.164-7.el7_8.2.x86_64              6/30 
  Updating   : 7:device-mapper-1.02.164-7.el7_8.2.x86_64                   7/30 
  Updating   : curl-7.29.0-57.el7_8.1.x86_64                               8/30 
  Updating   : 32:bind-license-9.11.4-16.P2.el7_8.6.noarch                 9/30 
  Updating   : tzdata-2020a-1.el7.noarch                                  10/30 
  Updating   : yum-plugin-ovl-1.1.31-54.el7_8.noarch                      11/30 
  Updating   : yum-utils-1.1.31-54.el7_8.noarch                           12/30 
  Updating   : binutils-2.27-43.base.el7_8.1.x86_64                       13/30

```
Can you see if you get the same error @JameelNabbo , @beaviss ?  Here is the Dockerfile I have been trying to adapt:
```
# using centos minimal centos:7.8.2003
FROM centos:7.8.2003
 
LABEL version = "1.0.0"
LABEL author =  "Michael Hidalgo" 

# checking if there are updates 
RUN yum update -y


CMD ["echo", "Hello, World"]
```

I'm going to spend some time on option **#1 Build a docker image from the Minimal Centos OS**

**Comment by michaelhidalgo** [comment]
Option # 3 "Using Linux Alpine" is getting more traction, specifically because that enforces hardening as explained in this great articles : 

- [https://medium.com/@michaeldimoudis/hardening-asp-net-core-3-1-docker-images-f0c2ede1667f](https://medium.com/@michaeldimoudis/hardening-asp-net-core-3-1-docker-images-f0c2ede1667f)
[https://medium.com/asos-techblog/minimising-your-attack-surface-by-building-highly-specialised-docker-images-example-for-net-b7bb177ab647](https://medium.com/asos-techblog/minimising-your-attack-surface-by-building-highly-specialised-docker-images-example-for-net-b7bb177ab647)

**Comment by zaddy6** [comment]
@michaelhidalgo I figured with Linux Alpine, trivy doesn't find any issues/vulnerabilities,  also even after running the harden.sh script during the build stage, the centos image still has about 656 vulnerabilities

**Comment by michaelhidalgo** [comment]
That's correct @zaddy6 , out of the box, Linux Alpine is clean, and we could raise the bar even more by creating a harden script for things like not running nginx as root :)

**Comment by JameelNabbo** [comment]
@michaelhidalgo  shall we sort the high issues manually? or just switch to Alpine?

**Comment by michaelhidalgo** [comment]
So additional to the current patching of the image, OpenSCAP seems to be a good option for leveling up the security of the image https://github.com/k8-proxy/k8-security/issues/63
