### ISSUE TITLE
Identify data protection coverage and control gaps in GW policies

### ISSUE THREAD

**Issue by jcanales** [k8-proxy/k8-security#38]

**Comment by Infospectives** [comment]
14/09 - Initial review of Data Protecton related [GW Security policies](https://github.com/filetrust/Glasswall-Security-Policies/tree/master/policies) and Data Protection compliance of main glasswallsolutions.com website cookie banner and privacy policy.
16/09 - Initial findings written up and shared with @PEpetra to flag that gaps exist, but full review would fall outside work planned for project. Pending discussion with Abbas on preferred next steps.

**Comment by Infospectives** [comment]
22/09 - Met with Abbas and Petra to confirm next steps. This issue to be closed and replaced with a milestone as discussed 3pm 22/09 with @jcanales.

1. @Infospectives to provide guidance and template to create Record of Processing Activity - Issue #43 and couments uploaded to repo docs folder - With Petra to review push and Abbas to progress
2. @Infospectives to provide overview of required policy changes to make GW security policies Data Protection compliant for project ICAP purposes and note implications of extending policy update to wider business e.g. change in formal data proection processing role, requirement to update data processing agreements and potentially update data controller privacy notices.
