### ISSUE TITLE
Provide Christina Diao definition of confidential data.

### ISSUE THREAD

**Issue by jcanales** [k8-proxy/k8-security#49]

**Comment by Infospectives** [comment]
Sub-task for Issue #38 

### Objective: 

Taking definition of 'Confidential Data' from Glasswall Data Classification policy and adding project-specific context.

### Inputs: 

- Glasswall [Data Classification policy](https://github.com/filetrust/Glasswall-Security-Policies/blob/master/policies/data-classification-policy.md)
- Glasswall [Confidential Data policy](https://github.com/filetrust/Glasswall-Security-Policies/blob/master/policies/Confidential%20Data.md)
- Glasswall [Information Asset Management policy](https://github.com/filetrust/Glasswall-Security-Policies/blob/master/policies/Information%20Asset%20Management%20Policy.md)
- [GDPR Article 4 definitions](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=EN#d1e1489-1-1)

### Current and amended data classification (for review):

NB: Current details taken without amendment from existing GW policies

**Current Overview**
Confidential data is typically the data that holds the most value to a company. Often, confidential data is valuable to others as well, and thus can carry greater risk than general company data. For these reasons, it is good practice to dictate security standards that relate specifically to confidential data

**Current Examples**
The following list is not intended to be exhaustive, but should provide the company with guidelines on what type of information is typically considered confidential. Confidential data can include:

- Employee or customer social security numbers or personal information.
- Medical and healthcare information.
- Customer data.
- Company financial data.
- Sales forecasts.
- Product and/or service plans, details, and schematics.
- Network diagrams and security configurations.
- Communications about corporate legal matters.
- Passwords.
- Banking information.
- Payroll information.
- Credit card information.
- Any confidential data held for a third party (be sure to adhere to any confidential data agreement covering such information)

### Other related tasks / documents:

- Task #43 Record of Processing Activity
- Task #19 Vulnerability CVSS scoring for project
- Task #45 Risk triage criteria for project
