### ISSUE TITLE
Define Static and dynamic analysis of pipeline

### ISSUE THREAD

**Issue by jcanales** [k8-proxy/k8-security#50]
Define tools, GitHub actions, and how this will take place.

**Comment by JameelNabbo** [comment]
Can we create this on a document and share it between all of us we can just post here in the comments?

**Comment by JameelNabbo** [comment]
Hi @jcanales  can we have a list of the technologies that the developers use so we can choose the right tools for them?

**Comment by beaviss** [comment]
Added some tools to the doc: https://docs.google.com/document/d/1amai4AvBbqoS00QctmBwIqET0tSdBHHK5mmWRjOAgP4/edit
SonarQube
Micro Focus Fortify SCA
OWASP ZAP
Burp Suite Enterprise and Professional

**Comment by JameelNabbo** [comment]
Have sent the following questions to Petra and waiting for her answer.

Write all the questions to petra regarding the SAST tools.

Please list the lines of code (LOC) for each technology/ language is used in the projects
Example (Java: 300K, JavaScript: 450K).

The programming languages and technologies used by the developers are (is that correct?):
C++
C# (MVC,.NET Core)
Java
JavaScript
NodeJS
React
Python

What CI/CD environment is used by the dev team e.g. GitLab, GitHub...

While there are SAST and DAST there's also IAST (Interactive Application Security Testing), do you require functional testing besides doing the security testing SAST and DAST?


Do you require the solution provider to scan Github or any version control systems commits and disallow them from commit while there's a security issue in the code?

What version control system you are using.

Are you using Azure or AWS or others or all of them?

How many developers are in the team (overall).

**Comment by JameelNabbo** [comment]
The first draft about SAST and DAST solutions according to the requirements I gathered from Petra today.

[Static and Dynamic analysis pipeline.docx](https://github.com/k8-proxy/k8-security/files/5272140/Static.and.Dynamic.analysis.pipeline.docx)

**Comment by jcanales** [comment]
Thanks @JameelNabbo
