### ISSUE TITLE
Assess vulnerabilities in k8-reverse-proxy project and followup

### ISSUE THREAD

**Issue by jcanales** [k8-proxy/k8-security#53]
Assess vulnerabilities in k8-reverse-proxy, these vulnerabilities are in this document tinyurl.com/y2menszt

- Review each and one of them.
- Evaluate if are relevant to the project.
- Create issues in the current repo so one of the devs can solve them.

**Comment by virajut** [comment]
@jcanales Putting this on hold until we've hardended images / alternative mechanism in place

**Comment by virajut** [comment]
Here we can follow two approach:

1. Use CentOS hardened image and install project dependencies / libraries on top of it for running particular services
2. Use base image from the Docker hub, harden it, push it to GW Docker hub and use it for running particular services

While pushing it to GW Docker hub account, CI / CD pipeline can be setup where it checks for vulnerabilities around and reject the push. On rejection, Security team can look into the case and fix it as required.
 
This same approach can be applied to #52 and for k8-test-data project as well.
