### ISSUE TITLE
Research incident response companies in UK

### ISSUE THREAD

**Issue by jcanales** [k8-proxy/k8-security#73]

**Comment by JameelNabbo** [comment]
Some companies from the list below ask for RFPs, will work on that.

PWC UK 
https://www2.deloitte.com/uk/en/pages/risk/articles/cyber-incident-response.html
https://www.nettitude.com/uk/incident-response/#RequestAFreeQuote
NCC group UK

**Comment by JameelNabbo** [comment]
This task already done
