### ISSUE TITLE
Implement sonarqube

### ISSUE THREAD

**Issue by jcanales** [k8-proxy/k8-security#90]

**Comment by JameelNabbo** [comment]
The current status of this task is we've implemented SonarCloud on the repo provided by Petra "ICAP Proxy" and now we are able to scan the C# and the C code however, we are in the final touches of this implementation

**Comment by JameelNabbo** [comment]
This task is completed on ICAP projects and now waiting for Petra's commands to start on glasswall side I'm responsible for this, I think this could be in another task.

@jcanales  this one can be closed.
